### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by chocopowwwa** [MartinLabs/generator-martinlabs#2]
Looks like the project need somekind of  pre-defined table? 
do you mind to provide the DDL?

**Comment by melanke** [comment]
This generator uses a mysql database running on your machine and generates a code that works with this database. What do you mean by DLL?

**Comment by melanke** [comment]
Oh! Martinlabs commons? Yep, we will update the maven repo, but in the meanwhile I will put on github this weak

**Comment by melanke** [comment]
https://bitbucket.org/martinlabs/martin.labs-java-commons/
